
env:
  es6: true
  node: true
  browser: false
extends: airbnb-base
parserOptions:
  ecmaVersion: 2017
rules:
  indent:
  - error
  - 2
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - single
  semi:
  - error
  - never
  prefer-template: error
  array-bracket-spacing:
  - error
  - always
  camelcase: warn
  no-useless-escape: warn
  no-nested-ternary: warn
  no-sequences: warn
  no-plusplus: warn
  import/no-extraneous-dependencies: warn
  max-len: warn
